sudo: false
language: node_js
node_js:
  - stable
cache: 
  directories: 
    - node_modules
install:
  - yarn install
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database teamwork_test;' -U postgres
  - 'yarn run syncTablesTest'
script:
  - 'yarn run test'
after_success:
  - 'yarn run coverage'