sudo: false
language: node_js
node_js:
  - stable
install:
  - yarn install
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE teamwork_test;" -U postgres
  - psql -c "CREATE USER gbrian WITH PASSWORD '00005';" -U postgres
  - yarn run syncTablesTest
script:
  - yarn test
after_success:
  - yarn run coverage
