sudo: false
language: node_js
node_js:
  - stable
cache: 
  directories: 
    - node_modules
install:
  - npm install
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database teamwork_test;' -U postgres
  - 'npm run syncTables'
script:
  - 'npm run test'
after_success:
  - 'npm run coverage'